# Generated by Django 3.2.16 on 2022-12-16 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20221216_0414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.IntegerField(choices=[(2, 'Владелец'), (1, 'Отдел закупок'), (0, 'Сотрудник')], verbose_name='Должность'),
        ),
    ]
