# Generated by Django 3.2.16 on 2022-12-16 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_profile_status'),
        ('control', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='providers', to='accounts.company', verbose_name='Компания'),
        ),
    ]
