# Generated by Django 3.2.16 on 2022-12-16 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_profile_status'),
        ('control', '0002_alter_provider_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='accounts.company', verbose_name='Компания'),
            preserve_default=False,
        ),
    ]
