# Generated by Django 3.2.16 on 2022-12-16 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0003_product_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='contract',
            field=models.FileField(blank=True, null=True, upload_to='media/contacts'),
        ),
    ]
