# Generated by Django 3.2.16 on 2022-12-16 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_profile_status'),
        ('control', '0005_alter_provider_contract'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternalContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract', models.FileField(upload_to='contracts/internal/', verbose_name='Договор')),
                ('date', models.DateTimeField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internal_contracts', to='accounts.company', verbose_name='Компания')),
            ],
            options={
                'verbose_name': 'Внутренний договор',
                'verbose_name_plural': 'Внутренние договоры',
            },
        ),
        migrations.CreateModel(
            name='ExternalContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract', models.FileField(upload_to='contracts/external/', verbose_name='Договор')),
                ('date', models.DateTimeField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_contracts', to='accounts.company', verbose_name='Компания')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='control.provider', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Внутренний договор',
                'verbose_name_plural': 'Внутренние договоры',
            },
        ),
    ]
