# Generated by Django 3.2.16 on 2022-12-16 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0007_auto_20221216_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.IntegerField(choices=[(0, 'Cоздана'), (4, 'Отклонена'), (1, 'Отправлена'), (2, 'Принята'), (3, 'Завершена')], default=0, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='internalcontract',
            name='contract',
            field=models.FilePathField(path='/Users/alexandrzhyliuk/Documents/cases/courses/zhilinskaya/back/app/media/contracts/', verbose_name='Договор'),
        ),
    ]
