# Generated by Django 3.2.16 on 2022-12-17 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0008_auto_20221216_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(0, 'Создан'), (1, 'Сформирован')], default=0, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.IntegerField(choices=[(0, 'Cоздана'), (3, 'Завершена'), (2, 'Принята'), (1, 'Отправлена'), (4, 'Отклонена')], default=0, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='orderpart',
            name='amount',
            field=models.IntegerField(blank=True, null=True, verbose_name='Кол-во'),
        ),
        migrations.AlterField(
            model_name='orderpart',
            name='cost',
            field=models.FloatField(blank=True, null=True, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='orderpart',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_parts', to='control.providerproduct', verbose_name='Товар'),
        ),
    ]
