# Generated by Django 3.2.16 on 2022-12-17 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0009_auto_20221217_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.IntegerField(choices=[(0, 'Cоздана'), (4, 'Отклонена'), (1, 'Отправлена'), (3, 'Завершена'), (2, 'Принята')], default=0, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='order',
            name='cost',
            field=models.FloatField(blank=True, null=True, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(1, 'Сформирован'), (0, 'Создан')], default=0, verbose_name='Статус'),
        ),
    ]
