# Generated by Django 3.2.16 on 2022-12-17 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0010_auto_20221217_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='order',
            name='fio',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ФИО получателя'),
        ),
        migrations.AddField(
            model_name='orderpart',
            name='requirement',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='control.requirement', verbose_name='Требование'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.IntegerField(choices=[(3, 'Завершена'), (1, 'Отправлена'), (4, 'Отклонена'), (0, 'Cоздана'), (2, 'Принята')], default=0, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(0, 'Создан'), (1, 'Сформирован')], default=0, verbose_name='Статус'),
        ),
    ]
