# Generated by Django 3.2.16 on 2022-12-17 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0011_auto_20221217_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.IntegerField(choices=[(3, 'Завершена'), (4, 'Отклонена'), (1, 'Отправлена'), (0, 'Cоздана'), (2, 'Принята')], default=0, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='externalcontract',
            name='contract',
            field=models.FilePathField(path='/Users/alexandrzhyliuk/Documents/cases/courses/zhilinskaya/back/app/media/contracts/', verbose_name='Договор'),
        ),
    ]
